### ISSUE TITLE
hard-coded npm prefix in nightwatch config

### ISSUE THREAD

**Issue by meonkeys** [awatson1978/starrynight#4]
`configs/nightwatch/config.json` has `"server_path" : "/usr/local/lib/node_modules/starrynight/node_modules/selenium-server-standalone...`, but it should use the npm prefix instead of `/usr/local`.

On my system, prefix is `/usr`, so I get this error:

```
$ starrynight -survey acceptance
Launching StarryNight.  Analyzing meteor environment...
Detected a meteor instance...
Launching nightwatch bridge...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

I don't know if nightwatch has a way to use environment or command-line variables in the config file, so it may be necessary to pre-process the config file to use a dynamic npm prefix.

Found while testing PR #3.

**Comment by awatson1978** [comment]
Yup, yup.  Makes total sense.  Not entirely sure how to inject that value into the config though.  :/

Might need to dynamically generate the config file.  Or open it up, parse the json, and write a new value to server_path.

**Comment by meonkeys** [comment]
Aha, you _can_ [use environment variables in a nightwatch config file](https://github.com/beatfactor/nightwatch/blob/master/lib/runner/cli/clirunner.js#L93). I'll see if I can make this work.
