### ISSUE TITLE
Test tags

### ISSUE THREAD

**Issue by mrvbalc** [awatson1978/starrynight#87]
Hi,
Is there a way to run starrynight tests using tags 
http://nightwatchjs.org/guide#test-tags

**Comment by awatson1978** [comment]
Absolutely.  We regularly use commands such as the following during local development:

``` bash
starrynight --run-tests --type validation --tags accounts
starrynight --run-tests --framework nightwatch --tags mobile
```

**Comment by awatson1978** [comment]
Most all of the Nightwatch commands have been aliased in StarryNight.  Feel free to submit PRs if we've missed any.

https://github.com/awatson1978/starrynight/blob/develop/tool/frameworks/nightwatch.js#L75-L122

**Comment by mrvbalc** [comment]
cool thx,
and thx for the quick response :)

**Comment by awatson1978** [comment]
I happened to have been doing a bit of work on this today, as it happens.  There was a small typo that was fixed, `tag` vs `tags`.  The latest version of starrynight `3.8.13` matches the nightwatch API.

``` bash
npm install -g starrynight
starrynight run-tests --type validation --tag layout
```
